/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DonationCategory = IDL.Variant({
  'cash' : IDL.Null,
  'inKind' : IDL.Null,
  'grant' : IDL.Null,
});
export const Donation = IDL.Record({
  'id' : IDL.Nat,
  'memberId' : IDL.Opt(IDL.Principal),
  'date' : IDL.Int,
  'donorName' : IDL.Text,
  'notes' : IDL.Text,
  'category' : DonationCategory,
  'amount' : IDL.Float64,
});
export const EventStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const EventView = IDL.Record({
  'id' : IDL.Nat,
  'status' : EventStatus,
  'title' : IDL.Text,
  'registeredAttendees' : IDL.Vec(IDL.Principal),
  'maxAttendees' : IDL.Nat,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const MemberStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const MembershipRole = IDL.Variant({
  'member' : IDL.Null,
  'board' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : IDL.Principal,
  'status' : MemberStatus,
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'role' : MembershipRole,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProjectStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'onHold' : IDL.Null,
  'planning' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'endDate' : IDL.Int,
  'description' : IDL.Text,
  'spent' : IDL.Float64,
  'budget' : IDL.Float64,
  'startDate' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalActiveMembers' : IDL.Nat,
  'activeProjectsCount' : IDL.Nat,
  'totalDonationsSum' : IDL.Float64,
  'upcomingEventsCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDonation' : IDL.Func([Donation], [], []),
  'addEvent' : IDL.Func([EventView], [], []),
  'addMember' : IDL.Func([Member], [], []),
  'addProject' : IDL.Func([Project], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDonation' : IDL.Func([IDL.Nat], [], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteMember' : IDL.Func([IDL.Principal], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(EventView)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDonation' : IDL.Func([IDL.Nat], [IDL.Opt(Donation)], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(EventView)], ['query']),
  'getMember' : IDL.Func([IDL.Principal], [IDL.Opt(Member)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDonation' : IDL.Func([IDL.Nat, Donation], [], []),
  'updateEvent' : IDL.Func([IDL.Nat, EventView], [], []),
  'updateMember' : IDL.Func([IDL.Principal, Member], [], []),
  'updateProject' : IDL.Func([IDL.Nat, Project], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DonationCategory = IDL.Variant({
    'cash' : IDL.Null,
    'inKind' : IDL.Null,
    'grant' : IDL.Null,
  });
  const Donation = IDL.Record({
    'id' : IDL.Nat,
    'memberId' : IDL.Opt(IDL.Principal),
    'date' : IDL.Int,
    'donorName' : IDL.Text,
    'notes' : IDL.Text,
    'category' : DonationCategory,
    'amount' : IDL.Float64,
  });
  const EventStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const EventView = IDL.Record({
    'id' : IDL.Nat,
    'status' : EventStatus,
    'title' : IDL.Text,
    'registeredAttendees' : IDL.Vec(IDL.Principal),
    'maxAttendees' : IDL.Nat,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const MemberStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const MembershipRole = IDL.Variant({
    'member' : IDL.Null,
    'board' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : IDL.Principal,
    'status' : MemberStatus,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'role' : MembershipRole,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProjectStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'onHold' : IDL.Null,
    'planning' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'endDate' : IDL.Int,
    'description' : IDL.Text,
    'spent' : IDL.Float64,
    'budget' : IDL.Float64,
    'startDate' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalActiveMembers' : IDL.Nat,
    'activeProjectsCount' : IDL.Nat,
    'totalDonationsSum' : IDL.Float64,
    'upcomingEventsCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDonation' : IDL.Func([Donation], [], []),
    'addEvent' : IDL.Func([EventView], [], []),
    'addMember' : IDL.Func([Member], [], []),
    'addProject' : IDL.Func([Project], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDonation' : IDL.Func([IDL.Nat], [], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteMember' : IDL.Func([IDL.Principal], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(EventView)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDonation' : IDL.Func([IDL.Nat], [IDL.Opt(Donation)], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(EventView)], ['query']),
    'getMember' : IDL.Func([IDL.Principal], [IDL.Opt(Member)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDonation' : IDL.Func([IDL.Nat, Donation], [], []),
    'updateEvent' : IDL.Func([IDL.Nat, EventView], [], []),
    'updateMember' : IDL.Func([IDL.Principal, Member], [], []),
    'updateProject' : IDL.Func([IDL.Nat, Project], [], []),
  });
};

export const init = ({ IDL }) => { return []; };