/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'totalActiveMembers' : bigint,
  'activeProjectsCount' : bigint,
  'totalDonationsSum' : number,
  'upcomingEventsCount' : bigint,
}
export interface Donation {
  'id' : bigint,
  'memberId' : [] | [Principal],
  'date' : bigint,
  'donorName' : string,
  'notes' : string,
  'category' : DonationCategory,
  'amount' : number,
}
export type DonationCategory = { 'cash' : null } |
  { 'inKind' : null } |
  { 'grant' : null };
export type EventStatus = { 'upcoming' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'ongoing' : null };
export interface EventView {
  'id' : bigint,
  'status' : EventStatus,
  'title' : string,
  'registeredAttendees' : Array<Principal>,
  'maxAttendees' : bigint,
  'date' : bigint,
  'description' : string,
  'location' : string,
}
export interface Member {
  'id' : Principal,
  'status' : MemberStatus,
  'joinDate' : bigint,
  'name' : string,
  'role' : MembershipRole,
  'email' : string,
  'notes' : string,
  'phone' : string,
}
export type MemberStatus = { 'active' : null } |
  { 'inactive' : null };
export type MembershipRole = { 'member' : null } |
  { 'board' : null } |
  { 'volunteer' : null };
export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'title' : string,
  'endDate' : bigint,
  'description' : string,
  'spent' : number,
  'budget' : number,
  'startDate' : bigint,
}
export type ProjectStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'onHold' : null } |
  { 'planning' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDonation' : ActorMethod<[Donation], undefined>,
  'addEvent' : ActorMethod<[EventView], undefined>,
  'addMember' : ActorMethod<[Member], undefined>,
  'addProject' : ActorMethod<[Project], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDonation' : ActorMethod<[bigint], undefined>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteMember' : ActorMethod<[Principal], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'getAllDonations' : ActorMethod<[], Array<Donation>>,
  'getAllEvents' : ActorMethod<[], Array<EventView>>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDonation' : ActorMethod<[bigint], [] | [Donation]>,
  'getEvent' : ActorMethod<[bigint], [] | [EventView]>,
  'getMember' : ActorMethod<[Principal], [] | [Member]>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDonation' : ActorMethod<[bigint, Donation], undefined>,
  'updateEvent' : ActorMethod<[bigint, EventView], undefined>,
  'updateMember' : ActorMethod<[Principal, Member], undefined>,
  'updateProject' : ActorMethod<[bigint, Project], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];