/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ConstitutionChapter = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'chapterNumber' : IDL.Nat,
});
export const ExpenseCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
});
export const ExpenseRecord = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'proofFileId' : IDL.Text,
  'serialNumber' : IDL.Nat,
  'category' : IDL.Text,
  'mobile' : IDL.Text,
  'recipientAddress' : IDL.Text,
  'amount' : IDL.Float64,
  'recipientName' : IDL.Text,
});
export const IncomeRecord = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'designation' : IDL.Text,
  'donorName' : IDL.Text,
  'donorAddress' : IDL.Text,
  'serialNumber' : IDL.Nat,
  'category' : IDL.Text,
  'mobile' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Council = IDL.Variant({
  'upadeshataParishad' : IDL.Null,
  'sadharanParishad' : IDL.Null,
  'karyanirbahaParishad' : IDL.Null,
});
export const CouncilMember = IDL.Record({
  'id' : IDL.Nat,
  'council' : Council,
  'designation' : IDL.Text,
  'email' : IDL.Text,
  'permanentAddress' : IDL.Text,
  'serialNumber' : IDL.Nat,
  'fatherName' : IDL.Text,
  'bloodGroup' : IDL.Text,
  'memberName' : IDL.Text,
  'currentAddress' : IDL.Text,
  'mobile' : IDL.Text,
});
export const NoticeRecord = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'date' : IDL.Text,
  'savedAt' : IDL.Text,
  'authority' : IDL.Text,
  'noticeNo' : IDL.Text,
});
export const ResolutionRecord = IDL.Record({
  'id' : IDL.Nat,
  'resolutions' : IDL.Text,
  'venue' : IDL.Text,
  'date' : IDL.Text,
  'meetingType' : IDL.Text,
  'secretary' : IDL.Text,
  'attendees' : IDL.Text,
  'savedAt' : IDL.Text,
  'presiding' : IDL.Text,
  'resNo' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FamilyNode = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'parentId' : IDL.Opt(IDL.Text),
  'generationLevel' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addChapter' : IDL.Func([IDL.Text, IDL.Text], [ConstitutionChapter], []),
  'addExpenseCategory' : IDL.Func([IDL.Text], [ExpenseCategory], []),
  'addExpenseRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [ExpenseRecord],
      [],
    ),
  'addIncomeRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IncomeRecord],
      [],
    ),
  'addMember' : IDL.Func(
      [
        Council,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [CouncilMember],
      [],
    ),
  'addNotice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [NoticeRecord],
      [],
    ),
  'addResolution' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [ResolutionRecord],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkExport' : IDL.Func([], [IDL.Text], ['query']),
  'bulkImport' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'message' : IDL.Text,
          'success' : IDL.Bool,
          'counts' : IDL.Text,
        }),
      ],
      [],
    ),
  'deleteChapter' : IDL.Func([IDL.Nat], [], []),
  'deleteExpenseCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteExpenseRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteFamilyNode' : IDL.Func([IDL.Text], [], []),
  'deleteIncomeRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteMember' : IDL.Func([IDL.Nat], [], []),
  'deleteNotice' : IDL.Func([IDL.Nat], [], []),
  'deleteResolution' : IDL.Func([IDL.Nat], [], []),
  'getAllChapters' : IDL.Func([], [IDL.Vec(ConstitutionChapter)], ['query']),
  'getAllExpenseCategories' : IDL.Func(
      [],
      [IDL.Vec(ExpenseCategory)],
      ['query'],
    ),
  'getAllExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
  'getAllFamilyNodes' : IDL.Func([], [IDL.Vec(FamilyNode)], ['query']),
  'getAllIncomeRecords' : IDL.Func([], [IDL.Vec(IncomeRecord)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(CouncilMember)], ['query']),
  'getAllNotices' : IDL.Func([], [IDL.Vec(NoticeRecord)], ['query']),
  'getAllResolutions' : IDL.Func([], [IDL.Vec(ResolutionRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMembersByCouncil' : IDL.Func(
      [Council],
      [IDL.Vec(CouncilMember)],
      ['query'],
    ),
  'getNextSerialNumber' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAllFamilyNodes' : IDL.Func([IDL.Vec(FamilyNode)], [], []),
  'updateChapter' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateExpenseRecord' : IDL.Func([IDL.Nat, ExpenseRecord], [], []),
  'updateIncomeRecord' : IDL.Func([IDL.Nat, IncomeRecord], [], []),
  'updateMember' : IDL.Func([IDL.Nat, CouncilMember], [], []),
  'upsertFamilyNode' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
      [FamilyNode],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ConstitutionChapter = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'chapterNumber' : IDL.Nat,
  });
  const ExpenseCategory = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const ExpenseRecord = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'proofFileId' : IDL.Text,
    'serialNumber' : IDL.Nat,
    'category' : IDL.Text,
    'mobile' : IDL.Text,
    'recipientAddress' : IDL.Text,
    'amount' : IDL.Float64,
    'recipientName' : IDL.Text,
  });
  const IncomeRecord = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'designation' : IDL.Text,
    'donorName' : IDL.Text,
    'donorAddress' : IDL.Text,
    'serialNumber' : IDL.Nat,
    'category' : IDL.Text,
    'mobile' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Council = IDL.Variant({
    'upadeshataParishad' : IDL.Null,
    'sadharanParishad' : IDL.Null,
    'karyanirbahaParishad' : IDL.Null,
  });
  const CouncilMember = IDL.Record({
    'id' : IDL.Nat,
    'council' : Council,
    'designation' : IDL.Text,
    'email' : IDL.Text,
    'permanentAddress' : IDL.Text,
    'serialNumber' : IDL.Nat,
    'fatherName' : IDL.Text,
    'bloodGroup' : IDL.Text,
    'memberName' : IDL.Text,
    'currentAddress' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const NoticeRecord = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'date' : IDL.Text,
    'savedAt' : IDL.Text,
    'authority' : IDL.Text,
    'noticeNo' : IDL.Text,
  });
  const ResolutionRecord = IDL.Record({
    'id' : IDL.Nat,
    'resolutions' : IDL.Text,
    'venue' : IDL.Text,
    'date' : IDL.Text,
    'meetingType' : IDL.Text,
    'secretary' : IDL.Text,
    'attendees' : IDL.Text,
    'savedAt' : IDL.Text,
    'presiding' : IDL.Text,
    'resNo' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FamilyNode = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'parentId' : IDL.Opt(IDL.Text),
    'generationLevel' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addChapter' : IDL.Func([IDL.Text, IDL.Text], [ConstitutionChapter], []),
    'addExpenseCategory' : IDL.Func([IDL.Text], [ExpenseCategory], []),
    'addExpenseRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
        ],
        [ExpenseRecord],
        [],
      ),
    'addIncomeRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
        ],
        [IncomeRecord],
        [],
      ),
    'addMember' : IDL.Func(
        [
          Council,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [CouncilMember],
        [],
      ),
    'addNotice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [NoticeRecord],
        [],
      ),
    'addResolution' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [ResolutionRecord],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkExport' : IDL.Func([], [IDL.Text], ['query']),
    'bulkImport' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'message' : IDL.Text,
            'success' : IDL.Bool,
            'counts' : IDL.Text,
          }),
        ],
        [],
      ),
    'deleteChapter' : IDL.Func([IDL.Nat], [], []),
    'deleteExpenseCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteExpenseRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteFamilyNode' : IDL.Func([IDL.Text], [], []),
    'deleteIncomeRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteMember' : IDL.Func([IDL.Nat], [], []),
    'deleteNotice' : IDL.Func([IDL.Nat], [], []),
    'deleteResolution' : IDL.Func([IDL.Nat], [], []),
    'getAllChapters' : IDL.Func([], [IDL.Vec(ConstitutionChapter)], ['query']),
    'getAllExpenseCategories' : IDL.Func(
        [],
        [IDL.Vec(ExpenseCategory)],
        ['query'],
      ),
    'getAllExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
    'getAllFamilyNodes' : IDL.Func([], [IDL.Vec(FamilyNode)], ['query']),
    'getAllIncomeRecords' : IDL.Func([], [IDL.Vec(IncomeRecord)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(CouncilMember)], ['query']),
    'getAllNotices' : IDL.Func([], [IDL.Vec(NoticeRecord)], ['query']),
    'getAllResolutions' : IDL.Func([], [IDL.Vec(ResolutionRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMembersByCouncil' : IDL.Func(
        [Council],
        [IDL.Vec(CouncilMember)],
        ['query'],
      ),
    'getNextSerialNumber' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAllFamilyNodes' : IDL.Func([IDL.Vec(FamilyNode)], [], []),
    'updateChapter' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateExpenseRecord' : IDL.Func([IDL.Nat, ExpenseRecord], [], []),
    'updateIncomeRecord' : IDL.Func([IDL.Nat, IncomeRecord], [], []),
    'updateMember' : IDL.Func([IDL.Nat, CouncilMember], [], []),
    'upsertFamilyNode' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
        [FamilyNode],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };