/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConstitutionChapter {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'chapterNumber' : bigint,
}
export type Council = { 'upadeshataParishad' : null } |
  { 'sadharanParishad' : null } |
  { 'karyanirbahaParishad' : null };
export interface CouncilMember {
  'id' : bigint,
  'council' : Council,
  'designation' : string,
  'email' : string,
  'permanentAddress' : string,
  'serialNumber' : bigint,
  'fatherName' : string,
  'bloodGroup' : string,
  'memberName' : string,
  'currentAddress' : string,
  'mobile' : string,
}
export interface ExpenseCategory { 'id' : bigint, 'name' : string }
export interface ExpenseRecord {
  'id' : bigint,
  'date' : string,
  'proofFileId' : string,
  'serialNumber' : bigint,
  'category' : string,
  'mobile' : string,
  'recipientAddress' : string,
  'amount' : number,
  'recipientName' : string,
}
export interface FamilyNode {
  'id' : string,
  'name' : string,
  'parentId' : [] | [string],
  'generationLevel' : bigint,
}
export interface IncomeRecord {
  'id' : bigint,
  'date' : string,
  'designation' : string,
  'donorName' : string,
  'donorAddress' : string,
  'serialNumber' : bigint,
  'category' : string,
  'mobile' : string,
  'amount' : number,
}
export interface NoticeRecord {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'date' : string,
  'savedAt' : string,
  'authority' : string,
  'noticeNo' : string,
}
export interface ResolutionRecord {
  'id' : bigint,
  'resolutions' : string,
  'venue' : string,
  'date' : string,
  'meetingType' : string,
  'secretary' : string,
  'attendees' : string,
  'savedAt' : string,
  'presiding' : string,
  'resNo' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addChapter' : ActorMethod<[string, string], ConstitutionChapter>,
  'addExpenseCategory' : ActorMethod<[string], ExpenseCategory>,
  'addExpenseRecord' : ActorMethod<
    [string, string, string, string, string, number, string],
    ExpenseRecord
  >,
  'addIncomeRecord' : ActorMethod<
    [string, string, string, string, string, number, string],
    IncomeRecord
  >,
  'addMember' : ActorMethod<
    [Council, string, string, string, string, string, string, string, string],
    CouncilMember
  >,
  'addNotice' : ActorMethod<
    [string, string, string, string, string, string],
    NoticeRecord
  >,
  'addResolution' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    ResolutionRecord
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkExport' : ActorMethod<[], string>,
  'bulkImport' : ActorMethod<
    [string],
    { 'message' : string, 'success' : boolean, 'counts' : string }
  >,
  'deleteChapter' : ActorMethod<[bigint], undefined>,
  'deleteExpenseCategory' : ActorMethod<[bigint], undefined>,
  'deleteExpenseRecord' : ActorMethod<[bigint], undefined>,
  'deleteFamilyNode' : ActorMethod<[string], undefined>,
  'deleteIncomeRecord' : ActorMethod<[bigint], undefined>,
  'deleteMember' : ActorMethod<[bigint], undefined>,
  'deleteNotice' : ActorMethod<[bigint], undefined>,
  'deleteResolution' : ActorMethod<[bigint], undefined>,
  'getAllChapters' : ActorMethod<[], Array<ConstitutionChapter>>,
  'getAllExpenseCategories' : ActorMethod<[], Array<ExpenseCategory>>,
  'getAllExpenseRecords' : ActorMethod<[], Array<ExpenseRecord>>,
  'getAllFamilyNodes' : ActorMethod<[], Array<FamilyNode>>,
  'getAllIncomeRecords' : ActorMethod<[], Array<IncomeRecord>>,
  'getAllMembers' : ActorMethod<[], Array<CouncilMember>>,
  'getAllNotices' : ActorMethod<[], Array<NoticeRecord>>,
  'getAllResolutions' : ActorMethod<[], Array<ResolutionRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMembersByCouncil' : ActorMethod<[Council], Array<CouncilMember>>,
  'getNextSerialNumber' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAllFamilyNodes' : ActorMethod<[Array<FamilyNode>], undefined>,
  'updateChapter' : ActorMethod<[bigint, string, string], undefined>,
  'updateExpenseRecord' : ActorMethod<[bigint, ExpenseRecord], undefined>,
  'updateIncomeRecord' : ActorMethod<[bigint, IncomeRecord], undefined>,
  'updateMember' : ActorMethod<[bigint, CouncilMember], undefined>,
  'upsertFamilyNode' : ActorMethod<
    [string, string, [] | [string], bigint],
    FamilyNode
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];