/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ConstitutionChapter = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'chapterNumber' : IDL.Nat,
});
export const ExpenseCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
});
export const ExpenseRecord = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'proofFileId' : IDL.Text,
  'serialNumber' : IDL.Nat,
  'category' : IDL.Text,
  'mobile' : IDL.Text,
  'recipientAddress' : IDL.Text,
  'amount' : IDL.Float64,
  'recipientName' : IDL.Text,
});
export const IncomeRecord = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'designation' : IDL.Text,
  'donorName' : IDL.Text,
  'donorAddress' : IDL.Text,
  'serialNumber' : IDL.Nat,
  'category' : IDL.Text,
  'mobile' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Council = IDL.Variant({
  'upadeshataParishad' : IDL.Null,
  'sadharanParishad' : IDL.Null,
  'karyanirbahaParishad' : IDL.Null,
});
export const CouncilMember = IDL.Record({
  'id' : IDL.Nat,
  'council' : Council,
  'designation' : IDL.Text,
  'email' : IDL.Text,
  'permanentAddress' : IDL.Text,
  'serialNumber' : IDL.Nat,
  'fatherName' : IDL.Text,
  'bloodGroup' : IDL.Text,
  'memberName' : IDL.Text,
  'currentAddress' : IDL.Text,
  'mobile' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChapter' : IDL.Func([IDL.Text, IDL.Text], [ConstitutionChapter], []),
  'addExpenseCategory' : IDL.Func([IDL.Text], [ExpenseCategory], []),
  'addExpenseRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [ExpenseRecord],
      [],
    ),
  'addIncomeRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IncomeRecord],
      [],
    ),
  'addMember' : IDL.Func(
      [
        Council,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [CouncilMember],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteChapter' : IDL.Func([IDL.Nat], [], []),
  'deleteExpenseCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteExpenseRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteIncomeRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteMember' : IDL.Func([IDL.Nat], [], []),
  'getAllChapters' : IDL.Func([], [IDL.Vec(ConstitutionChapter)], ['query']),
  'getAllExpenseCategories' : IDL.Func(
      [],
      [IDL.Vec(ExpenseCategory)],
      ['query'],
    ),
  'getAllExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
  'getAllIncomeRecords' : IDL.Func([], [IDL.Vec(IncomeRecord)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(CouncilMember)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMembersByCouncil' : IDL.Func(
      [Council],
      [IDL.Vec(CouncilMember)],
      ['query'],
    ),
  'getNextSerialNumber' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateChapter' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateExpenseRecord' : IDL.Func([IDL.Nat, ExpenseRecord], [], []),
  'updateIncomeRecord' : IDL.Func([IDL.Nat, IncomeRecord], [], []),
  'updateMember' : IDL.Func([IDL.Nat, CouncilMember], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ConstitutionChapter = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'chapterNumber' : IDL.Nat,
  });
  const ExpenseCategory = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const ExpenseRecord = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'proofFileId' : IDL.Text,
    'serialNumber' : IDL.Nat,
    'category' : IDL.Text,
    'mobile' : IDL.Text,
    'recipientAddress' : IDL.Text,
    'amount' : IDL.Float64,
    'recipientName' : IDL.Text,
  });
  const IncomeRecord = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'designation' : IDL.Text,
    'donorName' : IDL.Text,
    'donorAddress' : IDL.Text,
    'serialNumber' : IDL.Nat,
    'category' : IDL.Text,
    'mobile' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Council = IDL.Variant({
    'upadeshataParishad' : IDL.Null,
    'sadharanParishad' : IDL.Null,
    'karyanirbahaParishad' : IDL.Null,
  });
  const CouncilMember = IDL.Record({
    'id' : IDL.Nat,
    'council' : Council,
    'designation' : IDL.Text,
    'email' : IDL.Text,
    'permanentAddress' : IDL.Text,
    'serialNumber' : IDL.Nat,
    'fatherName' : IDL.Text,
    'bloodGroup' : IDL.Text,
    'memberName' : IDL.Text,
    'currentAddress' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChapter' : IDL.Func([IDL.Text, IDL.Text], [ConstitutionChapter], []),
    'addExpenseCategory' : IDL.Func([IDL.Text], [ExpenseCategory], []),
    'addExpenseRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
        ],
        [ExpenseRecord],
        [],
      ),
    'addIncomeRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
        ],
        [IncomeRecord],
        [],
      ),
    'addMember' : IDL.Func(
        [
          Council,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [CouncilMember],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteChapter' : IDL.Func([IDL.Nat], [], []),
    'deleteExpenseCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteExpenseRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteIncomeRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteMember' : IDL.Func([IDL.Nat], [], []),
    'getAllChapters' : IDL.Func([], [IDL.Vec(ConstitutionChapter)], ['query']),
    'getAllExpenseCategories' : IDL.Func(
        [],
        [IDL.Vec(ExpenseCategory)],
        ['query'],
      ),
    'getAllExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
    'getAllIncomeRecords' : IDL.Func([], [IDL.Vec(IncomeRecord)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(CouncilMember)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMembersByCouncil' : IDL.Func(
        [Council],
        [IDL.Vec(CouncilMember)],
        ['query'],
      ),
    'getNextSerialNumber' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateChapter' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateExpenseRecord' : IDL.Func([IDL.Nat, ExpenseRecord], [], []),
    'updateIncomeRecord' : IDL.Func([IDL.Nat, IncomeRecord], [], []),
    'updateMember' : IDL.Func([IDL.Nat, CouncilMember], [], []),
  });
};

export const init = ({ IDL }) => { return []; };