/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ResolutionRecord {
    id: bigint;
    resolutions: string;
    venue: string;
    date: string;
    meetingType: string;
    secretary: string;
    attendees: string;
    savedAt: string;
    presiding: string;
    resNo: string;
}
export interface ExpenseCategory {
    id: bigint;
    name: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ExpenseRecord {
    id: bigint;
    date: string;
    proofFileId: string;
    serialNumber: bigint;
    category: string;
    mobile: string;
    recipientAddress: string;
    amount: number;
    recipientName: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CouncilMember {
    id: bigint;
    council: Council;
    designation: string;
    email: string;
    permanentAddress: string;
    serialNumber: bigint;
    fatherName: string;
    bloodGroup: string;
    memberName: string;
    currentAddress: string;
    mobile: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface NoticeRecord {
    id: bigint;
    title: string;
    body: string;
    date: string;
    savedAt: string;
    authority: string;
    noticeNo: string;
}
export interface IncomeRecord {
    id: bigint;
    date: string;
    designation: string;
    donorName: string;
    donorAddress: string;
    serialNumber: bigint;
    category: string;
    mobile: string;
    amount: number;
}
export interface ConstitutionChapter {
    id: bigint;
    title: string;
    content: string;
    chapterNumber: bigint;
}
export interface FamilyNode {
    id: string;
    name: string;
    parentId?: string;
    generationLevel: bigint;
}
export interface UserProfile {
    name: string;
}
export enum Council {
    upadeshataParishad = "upadeshataParishad",
    sadharanParishad = "sadharanParishad",
    karyanirbahaParishad = "karyanirbahaParishad"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addChapter(title: string, content: string): Promise<ConstitutionChapter>;
    addExpenseCategory(name: string): Promise<ExpenseCategory>;
    addExpenseRecord(date: string, category: string, recipientName: string, recipientAddress: string, mobile: string, amount: number, proofFileId: string): Promise<ExpenseRecord>;
    addIncomeRecord(date: string, category: string, donorName: string, donorAddress: string, mobile: string, amount: number, designation: string): Promise<IncomeRecord>;
    addMember(council: Council, memberName: string, fatherName: string, mobile: string, email: string, bloodGroup: string, currentAddress: string, permanentAddress: string, designation: string): Promise<CouncilMember>;
    addNotice(date: string, noticeNo: string, title: string, body: string, authority: string, savedAt: string): Promise<NoticeRecord>;
    addResolution(date: string, resNo: string, meetingType: string, venue: string, presiding: string, attendees: string, resolutions: string, secretary: string, savedAt: string): Promise<ResolutionRecord>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkExport(): Promise<string>;
    bulkImport(jsonData: string): Promise<{
        message: string;
        success: boolean;
        counts: string;
    }>;
    deleteChapter(id: bigint): Promise<void>;
    deleteExpenseCategory(id: bigint): Promise<void>;
    deleteExpenseRecord(id: bigint): Promise<void>;
    deleteFamilyNode(id: string): Promise<void>;
    deleteIncomeRecord(id: bigint): Promise<void>;
    deleteMember(id: bigint): Promise<void>;
    deleteNotice(id: bigint): Promise<void>;
    deleteResolution(id: bigint): Promise<void>;
    getAllChapters(): Promise<Array<ConstitutionChapter>>;
    getAllExpenseCategories(): Promise<Array<ExpenseCategory>>;
    getAllExpenseRecords(): Promise<Array<ExpenseRecord>>;
    getAllFamilyNodes(): Promise<Array<FamilyNode>>;
    getAllIncomeRecords(): Promise<Array<IncomeRecord>>;
    getAllMembers(): Promise<Array<CouncilMember>>;
    getAllNotices(): Promise<Array<NoticeRecord>>;
    getAllResolutions(): Promise<Array<ResolutionRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMembersByCouncil(council: Council): Promise<Array<CouncilMember>>;
    getNextSerialNumber(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAllFamilyNodes(nodes: Array<FamilyNode>): Promise<void>;
    updateChapter(id: bigint, title: string, content: string): Promise<void>;
    updateExpenseRecord(id: bigint, updated: ExpenseRecord): Promise<void>;
    updateIncomeRecord(id: bigint, updated: IncomeRecord): Promise<void>;
    updateMember(id: bigint, updated: CouncilMember): Promise<void>;
    upsertFamilyNode(id: string, name: string, parentId: string | null, generationLevel: bigint): Promise<FamilyNode>;
}
import type { Council as _Council, CouncilMember as _CouncilMember, FamilyNode as _FamilyNode, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addChapter(arg0: string, arg1: string): Promise<ConstitutionChapter> {
        if (this.processError) {
            try {
                const result = await this.actor.addChapter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChapter(arg0, arg1);
            return result;
        }
    }
    async addExpenseCategory(arg0: string): Promise<ExpenseCategory> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpenseCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpenseCategory(arg0);
            return result;
        }
    }
    async addExpenseRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: string): Promise<ExpenseRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpenseRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpenseRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addIncomeRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: string): Promise<IncomeRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncomeRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncomeRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addMember(arg0: Council, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<CouncilMember> {
        if (this.processError) {
            try {
                const result = await this.actor.addMember(to_candid_Council_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_CouncilMember_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMember(to_candid_Council_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_CouncilMember_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async addNotice(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<NoticeRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotice(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotice(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addResolution(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<ResolutionRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addResolution(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResolution(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkExport(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkExport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkExport();
            return result;
        }
    }
    async bulkImport(arg0: string): Promise<{
        message: string;
        success: boolean;
        counts: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImport(arg0);
            return result;
        }
    }
    async deleteChapter(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChapter(arg0);
            return result;
        }
    }
    async deleteExpenseCategory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpenseCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpenseCategory(arg0);
            return result;
        }
    }
    async deleteExpenseRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpenseRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpenseRecord(arg0);
            return result;
        }
    }
    async deleteFamilyNode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFamilyNode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFamilyNode(arg0);
            return result;
        }
    }
    async deleteIncomeRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIncomeRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIncomeRecord(arg0);
            return result;
        }
    }
    async deleteMember(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMember(arg0);
            return result;
        }
    }
    async deleteNotice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0);
            return result;
        }
    }
    async deleteResolution(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResolution(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResolution(arg0);
            return result;
        }
    }
    async getAllChapters(): Promise<Array<ConstitutionChapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChapters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChapters();
            return result;
        }
    }
    async getAllExpenseCategories(): Promise<Array<ExpenseCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenseCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenseCategories();
            return result;
        }
    }
    async getAllExpenseRecords(): Promise<Array<ExpenseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenseRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenseRecords();
            return result;
        }
    }
    async getAllFamilyNodes(): Promise<Array<FamilyNode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFamilyNodes();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFamilyNodes();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllIncomeRecords(): Promise<Array<IncomeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIncomeRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIncomeRecords();
            return result;
        }
    }
    async getAllMembers(): Promise<Array<CouncilMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembers();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembers();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotices(): Promise<Array<NoticeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotices();
            return result;
        }
    }
    async getAllResolutions(): Promise<Array<ResolutionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResolutions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResolutions();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembersByCouncil(arg0: Council): Promise<Array<CouncilMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembersByCouncil(to_candid_Council_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembersByCouncil(to_candid_Council_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNextSerialNumber(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextSerialNumber();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextSerialNumber();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAllFamilyNodes(arg0: Array<FamilyNode>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAllFamilyNodes(to_candid_vec_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAllFamilyNodes(to_candid_vec_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateChapter(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapter(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapter(arg0, arg1, arg2);
            return result;
        }
    }
    async updateExpenseRecord(arg0: bigint, arg1: ExpenseRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpenseRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpenseRecord(arg0, arg1);
            return result;
        }
    }
    async updateIncomeRecord(arg0: bigint, arg1: IncomeRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIncomeRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIncomeRecord(arg0, arg1);
            return result;
        }
    }
    async updateMember(arg0: bigint, arg1: CouncilMember): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMember(arg0, to_candid_CouncilMember_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMember(arg0, to_candid_CouncilMember_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upsertFamilyNode(arg0: string, arg1: string, arg2: string | null, arg3: bigint): Promise<FamilyNode> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertFamilyNode(arg0, arg1, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_FamilyNode_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertFamilyNode(arg0, arg1, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_FamilyNode_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CouncilMember_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CouncilMember): CouncilMember {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Council_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Council): Council {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_FamilyNode_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FamilyNode): FamilyNode {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    council: _Council;
    designation: string;
    email: string;
    permanentAddress: string;
    serialNumber: bigint;
    fatherName: string;
    bloodGroup: string;
    memberName: string;
    currentAddress: string;
    mobile: string;
}): {
    id: bigint;
    council: Council;
    designation: string;
    email: string;
    permanentAddress: string;
    serialNumber: bigint;
    fatherName: string;
    bloodGroup: string;
    memberName: string;
    currentAddress: string;
    mobile: string;
} {
    return {
        id: value.id,
        council: from_candid_Council_n12(_uploadFile, _downloadFile, value.council),
        designation: value.designation,
        email: value.email,
        permanentAddress: value.permanentAddress,
        serialNumber: value.serialNumber,
        fatherName: value.fatherName,
        bloodGroup: value.bloodGroup,
        memberName: value.memberName,
        currentAddress: value.currentAddress,
        mobile: value.mobile
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    parentId: [] | [string];
    generationLevel: bigint;
}): {
    id: string;
    name: string;
    parentId?: string;
    generationLevel: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        parentId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.parentId)),
        generationLevel: value.generationLevel
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upadeshataParishad: null;
} | {
    sadharanParishad: null;
} | {
    karyanirbahaParishad: null;
}): Council {
    return "upadeshataParishad" in value ? Council.upadeshataParishad : "sadharanParishad" in value ? Council.sadharanParishad : "karyanirbahaParishad" in value ? Council.karyanirbahaParishad : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FamilyNode>): Array<FamilyNode> {
    return value.map((x)=>from_candid_FamilyNode_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CouncilMember>): Array<CouncilMember> {
    return value.map((x)=>from_candid_CouncilMember_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CouncilMember_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CouncilMember): _CouncilMember {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_Council_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Council): _Council {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_FamilyNode_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FamilyNode): _FamilyNode {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    parentId?: string;
    generationLevel: bigint;
}): {
    id: string;
    name: string;
    parentId: [] | [string];
    generationLevel: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        parentId: value.parentId ? candid_some(value.parentId) : candid_none(),
        generationLevel: value.generationLevel
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    council: Council;
    designation: string;
    email: string;
    permanentAddress: string;
    serialNumber: bigint;
    fatherName: string;
    bloodGroup: string;
    memberName: string;
    currentAddress: string;
    mobile: string;
}): {
    id: bigint;
    council: _Council;
    designation: string;
    email: string;
    permanentAddress: string;
    serialNumber: bigint;
    fatherName: string;
    bloodGroup: string;
    memberName: string;
    currentAddress: string;
    mobile: string;
} {
    return {
        id: value.id,
        council: to_candid_Council_n8(_uploadFile, _downloadFile, value.council),
        designation: value.designation,
        email: value.email,
        permanentAddress: value.permanentAddress,
        serialNumber: value.serialNumber,
        fatherName: value.fatherName,
        bloodGroup: value.bloodGroup,
        memberName: value.memberName,
        currentAddress: value.currentAddress,
        mobile: value.mobile
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Council): {
    upadeshataParishad: null;
} | {
    sadharanParishad: null;
} | {
    karyanirbahaParishad: null;
} {
    return value == Council.upadeshataParishad ? {
        upadeshataParishad: null
    } : value == Council.sadharanParishad ? {
        sadharanParishad: null
    } : value == Council.karyanirbahaParishad ? {
        karyanirbahaParishad: null
    } : value;
}
function to_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FamilyNode>): Array<_FamilyNode> {
    return value.map((x)=>to_candid_FamilyNode_n25(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
