/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EventView {
    id: bigint;
    status: EventStatus;
    title: string;
    registeredAttendees: Array<Principal>;
    maxAttendees: bigint;
    date: bigint;
    description: string;
    location: string;
}
export interface Donation {
    id: bigint;
    memberId?: Principal;
    date: bigint;
    donorName: string;
    notes: string;
    category: DonationCategory;
    amount: number;
}
export interface Member {
    id: Principal;
    status: MemberStatus;
    joinDate: bigint;
    name: string;
    role: MembershipRole;
    email: string;
    notes: string;
    phone: string;
}
export interface Project {
    id: bigint;
    status: ProjectStatus;
    title: string;
    endDate: bigint;
    description: string;
    spent: number;
    budget: number;
    startDate: bigint;
}
export interface DashboardStats {
    totalActiveMembers: bigint;
    activeProjectsCount: bigint;
    totalDonationsSum: number;
    upcomingEventsCount: bigint;
}
export interface UserProfile {
    name: string;
}
export enum DonationCategory {
    cash = "cash",
    inKind = "inKind",
    grant = "grant"
}
export enum EventStatus {
    upcoming = "upcoming",
    cancelled = "cancelled",
    completed = "completed",
    ongoing = "ongoing"
}
export enum MemberStatus {
    active = "active",
    inactive = "inactive"
}
export enum MembershipRole {
    member = "member",
    board = "board",
    volunteer = "volunteer"
}
export enum ProjectStatus {
    active = "active",
    completed = "completed",
    onHold = "onHold",
    planning = "planning"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDonation(donation: Donation): Promise<void>;
    addEvent(event: EventView): Promise<void>;
    addMember(member: Member): Promise<void>;
    addProject(project: Project): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteDonation(id: bigint): Promise<void>;
    deleteEvent(id: bigint): Promise<void>;
    deleteMember(id: Principal): Promise<void>;
    deleteProject(id: bigint): Promise<void>;
    getAllDonations(): Promise<Array<Donation>>;
    getAllEvents(): Promise<Array<EventView>>;
    getAllMembers(): Promise<Array<Member>>;
    getAllProjects(): Promise<Array<Project>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getDonation(id: bigint): Promise<Donation | null>;
    getEvent(id: bigint): Promise<EventView | null>;
    getMember(id: Principal): Promise<Member | null>;
    getProject(id: bigint): Promise<Project | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateDonation(id: bigint, updatedDonation: Donation): Promise<void>;
    updateEvent(id: bigint, updatedEvent: EventView): Promise<void>;
    updateMember(id: Principal, updatedMember: Member): Promise<void>;
    updateProject(id: bigint, updatedProject: Project): Promise<void>;
}
import type { Donation as _Donation, DonationCategory as _DonationCategory, EventStatus as _EventStatus, EventView as _EventView, Member as _Member, MemberStatus as _MemberStatus, MembershipRole as _MembershipRole, Project as _Project, ProjectStatus as _ProjectStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDonation(arg0: Donation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDonation(to_candid_Donation_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDonation(to_candid_Donation_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addEvent(arg0: EventView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(to_candid_EventView_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(to_candid_EventView_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMember(arg0: Member): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMember(to_candid_Member_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMember(to_candid_Member_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(to_candid_Project_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(to_candid_Project_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteDonation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDonation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDonation(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteMember(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMember(arg0);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async getAllDonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonations();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonations();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEvents(): Promise<Array<EventView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembers(): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembers();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembers();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDonation(arg0: bigint): Promise<Donation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonation(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonation(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: bigint): Promise<EventView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMember(arg0: Principal): Promise<Member | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMember(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMember(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateDonation(arg0: bigint, arg1: Donation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonation(arg0, to_candid_Donation_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonation(arg0, to_candid_Donation_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEvent(arg0: bigint, arg1: EventView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, to_candid_EventView_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, to_candid_EventView_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMember(arg0: Principal, arg1: Member): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMember(arg0, to_candid_Member_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMember(arg0, to_candid_Member_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProject(arg0: bigint, arg1: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_Project_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_Project_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_DonationCategory_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonationCategory): DonationCategory {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Donation_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donation): Donation {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_EventStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventStatus): EventStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_EventView_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventView): EventView {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_MemberStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberStatus): MemberStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Member_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Member): Member {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipRole): MembershipRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Donation]): Donation | null {
    return value.length === 0 ? null : from_candid_Donation_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EventView]): EventView | null {
    return value.length === 0 ? null : from_candid_EventView_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Member]): Member | null {
    return value.length === 0 ? null : from_candid_Member_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    memberId: [] | [Principal];
    date: bigint;
    donorName: string;
    notes: string;
    category: _DonationCategory;
    amount: number;
}): {
    id: bigint;
    memberId?: Principal;
    date: bigint;
    donorName: string;
    notes: string;
    category: DonationCategory;
    amount: number;
} {
    return {
        id: value.id,
        memberId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.memberId)),
        date: value.date,
        donorName: value.donorName,
        notes: value.notes,
        category: from_candid_DonationCategory_n25(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EventStatus;
    title: string;
    registeredAttendees: Array<Principal>;
    maxAttendees: bigint;
    date: bigint;
    description: string;
    location: string;
}): {
    id: bigint;
    status: EventStatus;
    title: string;
    registeredAttendees: Array<Principal>;
    maxAttendees: bigint;
    date: bigint;
    description: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_EventStatus_n30(_uploadFile, _downloadFile, value.status),
        title: value.title,
        registeredAttendees: value.registeredAttendees,
        maxAttendees: value.maxAttendees,
        date: value.date,
        description: value.description,
        location: value.location
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    status: _MemberStatus;
    joinDate: bigint;
    name: string;
    role: _MembershipRole;
    email: string;
    notes: string;
    phone: string;
}): {
    id: Principal;
    status: MemberStatus;
    joinDate: bigint;
    name: string;
    role: MembershipRole;
    email: string;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_MemberStatus_n35(_uploadFile, _downloadFile, value.status),
        joinDate: value.joinDate,
        name: value.name,
        role: from_candid_MembershipRole_n37(_uploadFile, _downloadFile, value.role),
        email: value.email,
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProjectStatus;
    title: string;
    endDate: bigint;
    description: string;
    spent: number;
    budget: number;
    startDate: bigint;
}): {
    id: bigint;
    status: ProjectStatus;
    title: string;
    endDate: bigint;
    description: string;
    spent: number;
    budget: number;
    startDate: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n42(_uploadFile, _downloadFile, value.status),
        title: value.title,
        endDate: value.endDate,
        description: value.description,
        spent: value.spent,
        budget: value.budget,
        startDate: value.startDate
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    inKind: null;
} | {
    grant: null;
}): DonationCategory {
    return "cash" in value ? DonationCategory.cash : "inKind" in value ? DonationCategory.inKind : "grant" in value ? DonationCategory.grant : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    ongoing: null;
}): EventStatus {
    return "upcoming" in value ? EventStatus.upcoming : "cancelled" in value ? EventStatus.cancelled : "completed" in value ? EventStatus.completed : "ongoing" in value ? EventStatus.ongoing : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): MemberStatus {
    return "active" in value ? MemberStatus.active : "inactive" in value ? MemberStatus.inactive : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: null;
} | {
    board: null;
} | {
    volunteer: null;
}): MembershipRole {
    return "member" in value ? MembershipRole.member : "board" in value ? MembershipRole.board : "volunteer" in value ? MembershipRole.volunteer : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    onHold: null;
} | {
    planning: null;
}): ProjectStatus {
    return "active" in value ? ProjectStatus.active : "completed" in value ? ProjectStatus.completed : "onHold" in value ? ProjectStatus.onHold : "planning" in value ? ProjectStatus.planning : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donation>): Array<Donation> {
    return value.map((x)=>from_candid_Donation_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EventView>): Array<EventView> {
    return value.map((x)=>from_candid_EventView_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Member>): Array<Member> {
    return value.map((x)=>from_candid_Member_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n40(_uploadFile, _downloadFile, x));
}
function to_candid_DonationCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationCategory): _DonationCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Donation_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Donation): _Donation {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_EventStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): _EventStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_EventView_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventView): _EventView {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_MemberStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberStatus): _MemberStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Member_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Member): _Member {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_MembershipRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipRole): _MembershipRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Project_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    status: MemberStatus;
    joinDate: bigint;
    name: string;
    role: MembershipRole;
    email: string;
    notes: string;
    phone: string;
}): {
    id: Principal;
    status: _MemberStatus;
    joinDate: bigint;
    name: string;
    role: _MembershipRole;
    email: string;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        status: to_candid_MemberStatus_n11(_uploadFile, _downloadFile, value.status),
        joinDate: value.joinDate,
        name: value.name,
        role: to_candid_MembershipRole_n13(_uploadFile, _downloadFile, value.role),
        email: value.email,
        notes: value.notes,
        phone: value.phone
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: ProjectStatus;
    title: string;
    endDate: bigint;
    description: string;
    spent: number;
    budget: number;
    startDate: bigint;
}): {
    id: bigint;
    status: _ProjectStatus;
    title: string;
    endDate: bigint;
    description: string;
    spent: number;
    budget: number;
    startDate: bigint;
} {
    return {
        id: value.id,
        status: to_candid_ProjectStatus_n17(_uploadFile, _downloadFile, value.status),
        title: value.title,
        endDate: value.endDate,
        description: value.description,
        spent: value.spent,
        budget: value.budget,
        startDate: value.startDate
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    memberId?: Principal;
    date: bigint;
    donorName: string;
    notes: string;
    category: DonationCategory;
    amount: number;
}): {
    id: bigint;
    memberId: [] | [Principal];
    date: bigint;
    donorName: string;
    notes: string;
    category: _DonationCategory;
    amount: number;
} {
    return {
        id: value.id,
        memberId: value.memberId ? candid_some(value.memberId) : candid_none(),
        date: value.date,
        donorName: value.donorName,
        notes: value.notes,
        category: to_candid_DonationCategory_n3(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: EventStatus;
    title: string;
    registeredAttendees: Array<Principal>;
    maxAttendees: bigint;
    date: bigint;
    description: string;
    location: string;
}): {
    id: bigint;
    status: _EventStatus;
    title: string;
    registeredAttendees: Array<Principal>;
    maxAttendees: bigint;
    date: bigint;
    description: string;
    location: string;
} {
    return {
        id: value.id,
        status: to_candid_EventStatus_n7(_uploadFile, _downloadFile, value.status),
        title: value.title,
        registeredAttendees: value.registeredAttendees,
        maxAttendees: value.maxAttendees,
        date: value.date,
        description: value.description,
        location: value.location
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == MemberStatus.active ? {
        active: null
    } : value == MemberStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipRole): {
    member: null;
} | {
    board: null;
} | {
    volunteer: null;
} {
    return value == MembershipRole.member ? {
        member: null
    } : value == MembershipRole.board ? {
        board: null
    } : value == MembershipRole.volunteer ? {
        volunteer: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    active: null;
} | {
    completed: null;
} | {
    onHold: null;
} | {
    planning: null;
} {
    return value == ProjectStatus.active ? {
        active: null
    } : value == ProjectStatus.completed ? {
        completed: null
    } : value == ProjectStatus.onHold ? {
        onHold: null
    } : value == ProjectStatus.planning ? {
        planning: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationCategory): {
    cash: null;
} | {
    inKind: null;
} | {
    grant: null;
} {
    return value == DonationCategory.cash ? {
        cash: null
    } : value == DonationCategory.inKind ? {
        inKind: null
    } : value == DonationCategory.grant ? {
        grant: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): {
    upcoming: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    ongoing: null;
} {
    return value == EventStatus.upcoming ? {
        upcoming: null
    } : value == EventStatus.cancelled ? {
        cancelled: null
    } : value == EventStatus.completed ? {
        completed: null
    } : value == EventStatus.ongoing ? {
        ongoing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
